/**
 * Regenerates src/fonts.js from assets/fonts/*.woff2.
 *
 * The report must render with no network, so the fonts travel inside it as
 * base64. Both are SIL OFL 1.1 (licences alongside), which permits embedding.
 * Run after changing a font file: node scripts/embed-fonts.mjs
 */

import { readFileSync, writeFileSync } from 'node:fs';

const b64 = (f) => readFileSync(new URL(`../assets/fonts/${f}`, import.meta.url)).toString('base64');

writeFileSync(new URL('../src/fonts.js', import.meta.url), `// GENERATED by scripts/embed-fonts.mjs. Do not edit.
// Space Grotesk and JetBrains Mono, latin subset, variable weight 400–700.
// SIL Open Font License 1.1, see assets/fonts/OFL-*.txt.

export const SPACE_GROTESK = '${b64('SpaceGrotesk-latin.woff2')}';
export const JETBRAINS_MONO = '${b64('JetBrainsMono-latin.woff2')}';
`);
